apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cricket-score-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KabraJiii/flask_app_CICD.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true