apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cricket-flask-app
  name: cricket-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cricket-flask-app
  strategy: {}
  template:
    metadata:
      labels:
        app: cricket-flask-app
    spec:
      containers:
      - image: kabrajii/crickflaskapp:latest
        name: crickflaskapp
        ports:
        - containerPort: 8080
    
